import 'dart:convert';
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'package:stones/puzzles/forcing_search.dart';
import 'package:stones/puzzles/square_forcing_position.dart';
import 'package:stones/puzzles/square_studies.dart';
import 'package:stones/puzzles/study.dart';
import 'package:stones/hex/hex_forcing_position.dart';
import 'package:stones/hex/hex_studies.dart';
import 'package:stones/puzzles/certificates.dart';

final _authored = <String, dynamic>{};

void audit<S, M>(List<Study<S>> studies, ForcingPosition<S, M> rules) {
  for (final study in studies) {
    test('prove ${study.id}', () {
      expect(study.moves, inInclusiveRange(1, 2),
          reason: 'Deeper studies need a policy for every human decision');
      final search = ForcingSearch(rules, rules.player(study.initial),
          nodeLimit: 10000000);
      final legal = rules.moves(study.initial).toList();
      final winning = search.winningMoves(study.initial, study.moves);
      // A finite-horizon objective must have a solution and genuine alternatives.
      expect(winning, isNotEmpty);
      expect(winning.length, lessThan(legal.length));
      if (study.moves > 1) {
        expect(search.wins(study.initial, study.moves - 1), isFalse);
      }
      final replies = <String, List<String>>{};
      final sample = <String>[];
      for (final move in legal) {
        var state = rules.play(study.initial, move);
        final good = winning.any(
            (candidate) => rules.moveKey(candidate) == rules.moveKey(move));
        final line = <String>[];
        while (!rules.finished(state) &&
            rules.player(state) != search.learner &&
            study.moves > 1) {
          M? reply;
          if (!good) reply = search.refutation(state, study.moves - 1);
          if (good) {
            var fewest = 1000000;
            for (final candidate in rules.moves(state)) {
              final child = rules.play(state, candidate);
              final threats = rules.finished(child)
                  ? 0
                  : search
                      .winningMoves(rules.learnerTurn(child, search.learner), 1)
                      .length;
              if (threats < fewest) {
                reply = candidate;
                fewest = threats;
              }
            }
          }
          expect(reply, isNotNull,
              reason: 'A losing root needs an actual refutation');
          line.add(rules.moveKey(reply as M));
          state = rules.play(state, reply);
        }
        replies[rules.moveKey(move)] = line;
        if (study.moves > 1) {
          expect(search.wins(state, study.moves - 1), good,
              reason:
                  'Representative defense must preserve or refute the objective');
        }
        if (good && sample.isEmpty) {
          sample.addAll([rules.moveKey(move), ...line]);
          if (!rules.finished(state)) {
            sample.add(rules.moveKey(search.winningMoves(state, 1).first));
          }
        }
      }
      final data = {
        'legal': legal.length,
        'winning': winning.map(rules.moveKey).toList(),
        'replies': replies,
        'sample': sample,
        'nodes': search.nodes
      };
      if (Platform.environment['STONES_AUTHOR_PUZZLES'] != '1') {
        final checkedIn = puzzleCertificates[study.id]!;
        for (final field in ['legal', 'winning', 'replies', 'sample']) {
          expect(data[field], checkedIn[field],
              reason: 'Stale certificate ${study.id}: $field');
        }
      }
      _authored[study.id] = data;
      // Opt-in authoring output; normal test runs never rewrite source data.
      // ignore: avoid_print
      print(
          '${study.id}: ${winning.map(rules.moveKey).join(" / ")} of ${legal.length}; ${search.nodes} nodes');
    }, timeout: const Timeout(Duration(minutes: 15)));
  }
}

void main() {
  tearDownAll(() {
    if (Platform.environment['STONES_AUTHOR_PUZZLES'] != '1') return;
    expect(_authored.length, squareStudies.length + hexStudies.length,
        reason:
            'Only a successful, complete catalog run may replace certificates');
    File('lib/puzzles/certificates.dart').writeAsStringSync(
        '// Generated by STONES_AUTHOR_PUZZLES=1 flutter test test/audit/puzzle_authoring_test.dart.\n// Exhaustive finite-horizon proofs; do not edit by hand.\nconst Map<String, Map<String, dynamic>> puzzleCertificates = ${const JsonEncoder.withIndent('  ').convert(_authored)};\n');
  });
  audit(squareStudies, SquareForcingPosition());
  audit(hexStudies, HexForcingPosition());
}
