import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase configuration.
///
/// Replace the values in [DefaultFirebaseOptions.currentPlatform] with your
/// Firebase project settings generated by the FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace with FirebaseOptions from your project using FlutterFire CLI.
    return const FirebaseOptions(
      apiKey: 'REPLACE_WITH_API_KEY',
      appId: 'REPLACE_WITH_APP_ID',
      messagingSenderId: 'REPLACE_WITH_SENDER_ID',
      projectId: 'REPLACE_WITH_PROJECT_ID',
      authDomain: 'REPLACE_WITH_AUTH_DOMAIN',
      storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    );
  }
}
